### ISSUE TITLE
Is there way to setColor and Clear color value

### ISSUE THREAD

**Issue by notrealdev** [R-TEK/colr_pickr#16]
Hi, is there way to:
- Set custom color like `.setColor( '#000000 )`
- Clear to color value to `''`

**Comment by R-TEK** [comment]
**To set a color:**
Syntax
colorPickerComp.colorChange([color], [Button which open the picker]);

Example:
colorPickerComp.colorChange('#000', document.getElementById('color-picker-button'));

**To clear a color**
Same as above but color is '' (empty string)

**Comment by notrealdev** [comment]
Thank you so much!
