### ISSUE TITLE
Pre-Open ColorPicker without button

### ISSUE THREAD

**Issue by erfanmola** [R-TEK/colr_pickr#3]
Hi, I was wondering if it is possible to have a pre-opened ColorPicker dialog in page, with no need of a button

I don't want it to be a popup that gets activated by clicking on a button, I want it as a section in my website which has to be shown already and be activated ASAP the page loads,  NOT A POPUP DIALOG

Any Ideas ?

**Comment by R-TEK** [comment]
Hi,

No this is not currently a featute in the color picker. I will add this idea to feature requests and may work on it in the future.

**Comment by erfanmola** [comment]
Thanks
