### ISSUE TITLE
colorPickerComp.colorChange doesnt work

### ISSUE THREAD

**Issue by vladgurgov** [R-TEK/colr_pickr#4]
**Details**
What browser were you using: Chrom
What OS were you using: Mac
Project version you have: latest

**Describe the bug**

I am using your main example and trying to change color from javascript

    colorPickerComp.colorChange('#ff00ff', button);

Later in colorChange event i am getting #NaNNaNNaNNaN as a color

When looking into your code that makes sense

 * @example
 * const button = document.getElementById('my_button');
 * colorPickerComp.colorChange('#ff0000', button);
 */
colorPickerComp.colorChange = function (color, elem) {
	// Defining the RGBA value conversion
	const rgbaValue = colorPickerComp.HSLAToRGBA(color.h, color.s, color.l, color.a);
	const hex = colorPickerComp.HSLAToRGBA(color.h, color.s, color.l, color.a, true);

How are you calling color.h, color.s, color.l, color.a of string '#ff00ff' 

This doesn't make sense to me, what am i missing?

**To Reproduce**
Run test code from your homepage

**Screenshots (Optional)**

**Additional context (Optional)**

**Comment by R-TEK** [comment]
Yep, I see what you mean. I made changes to this event in my last update and didnt realise it can also be used as an function to manually chnage a color.

I have a fix for this soon.

Thanks

**Comment by R-TEK** [comment]
@vladgurgov Fixed and pushed to the latest release tag v1.2.1
