### ISSUE TITLE
UI sugegstions

### ISSUE THREAD

**Issue by yairEO** [R-TEK/colr_pickr#7]
**How the process currently work.**
![image](https://user-images.githubusercontent.com/845031/99914770-5ee53500-2d08-11eb-83fa-1ab3c2179e71.png)

**How you believe the process can be improved.**
I've marked areas which I would like to provide some suggestions, as a designer and also as someone who will be using this wonderful picker:

Overall, the picker is quite large, and it seems to open only in the center of the screen and not next to the clicked/touched color input. I would expect it to behave similar to native color input in terms of position, because it's much easier not to move the mouse all the way far from where the user clicked only to set a color.

I also prefer not to have a dark opaque background like it was some modal window, it's too much. I get it that it's nice if you consider your widget a modal, but I would like something that is more aligned with the spec in terms of position.

Regarding the points I've marked:

1. I would completely remove the selected color, shown at `(2)` and stretch the sliders to full width,
and I would replace the selected color circle with what you already have, which is the circle at point `(1)`.
Currently that circle is too small, ***but***, it can be enlarged once hovered-out, therefore serving 2 purposes at once.

3. Bottom gap is not the same as top gap, which wastes space and looks strange:
![image](https://user-images.githubusercontent.com/845031/99915113-542b9f80-2d0a-11eb-8f33-3554f4d783a3.png)

4. Eliminate the wasted whitespace unless a color is added via the `+` button.
Also, the title uses non-standard terminology *"custom colors"*. I suggest nameing it: *"colors swatch"* or *"swatch palette"*, as commonly named in graphic editing software

**Additional context**
I initially wanted to use [Pickr](https://github.com/Simonwep/pickr) but it's large file-size deterred me.
After some digging I found yours and it seems the best so far in terms of UI & filesize. I hoped to get a much lower filesize...but I have no time to make such a component myself.. too many already on-going open-source projects.

Another thing - regarding your [homepage](https://r-tek.github.io/colr_pickr), it would be nice if a working demo was right on the landing page and not just a screenshot of the component.

**Comment by R-TEK** [comment]
@yairEO 

Thanks for the suggestions you have made. I understand the points you have made and agree with them, in particular making the picker component a widget next to the button as opposed to a modal in the center of the screen like I have it now. I've been thinking about this change for a while, but due to no feedback on the matter (until now) there has been no urgency to make the change.

I will most likely remove the modal view for the picker, and move over to the a widget only view, which I think is better anyway and this will keep down the file size.

Also, the attention to detail you have shown will be helpful in optimizing the UI.

I will be going through the suggestion and I'll work on the picker throughout the next few days. Anything else you'd like to add feel free to.

**Comment by yairEO** [comment]
You can use this for positioning your component:

https://github.com/Simonwep/nanopop

**Comment by R-TEK** [comment]
@yairEO
[UPDATE]

Found time today to work on the suggestions, I've added in everything you've mentioned now, I thought about each point and I agreed that making these edits will improve the color picker.

There are a few optimizations I want to make and then test everything, after this I will make a new release which I expect will be tomorrow or so.

The updated stuff is in the picker_popup branch if you want to play around or provide feedback.

**Comment by R-TEK** [comment]
@yairEO

The new version of the color picker is released under the master branch or v2.0.0 tag. This features the suggestions you made.

Let me know if you have any feedback.

**Comment by R-TEK** [comment]
@yairEO

Also, the suggestions you made on the project website are useful. I use a template I made to have websites for these projects quicker. But eventually I will get round to making a site specifically for the color picker.

**Comment by David-Carty** [comment]
I'm a minimalist, so I'd want to disable custom colors and limit to HEX only.  Great to have these as props.

**Comment by R-TEK** [comment]
@David-Carty Yeah, it could be useful for me to have some options where users are able to choose which sections they want to hide.
