### ISSUE TITLE
not working in IE11

### ISSUE THREAD

**Issue by siccolo** [R-TEK/colr_pickr#8]
**Details**
What browser were you using: IE11
What OS were you using: windows 10
Project version you have: navigate to https://r-tek.github.io/colr_pickr/get-started.html

**Describe the bug**
SCRIPT1014: Invalid character 
lib.js (41,8653)

: 'ColorPicker' is undefined
get-started.js (1,60)

**To Reproduce**
1. Go to  navigate to https://r-tek.github.io/colr_pickr/get-started.html

**Screenshots (Optional)**

**Additional context (Optional)**

**Comment by R-TEK** [comment]
@siccolo IE11 is not supported. Could run it through babel if you wanted to try though.

**Comment by R-TEK** [comment]
Closed
